cmake_minimum_required (VERSION 2.6)

# Añadimos los directorios
add_subdirectory(matrixAdd)
#add_subdirectory(Mandelbrot)
#add_subdirectory(BlackScholes)
#add_subdirectory(matrixMult)
#add_subdirectory(gemver)
#add_subdirectory(gemver_gpuxphi)
#add_subdirectory(matrixPowerOf)
#add_subdirectory(matrixPowerOf_gpuxphi)
#add_subdirectory(matrixTimesMatrix_gpuxphi)


#add_subdirectory(gpu+xphi)
