cmake_minimum_required (VERSION 2.6)

# Añadimos los directorios
add_subdirectory(mandelbrot_gpucpu)
add_subdirectory(matrixAdd_gpucpu)
add_subdirectory(matrixMult_gpucpu)
add_subdirectory(BlackScholes_gpucpu)
#add_subdirectory(gemver_gpuxphi)
#add_subdirectory(matrixPowerOf)
#add_subdirectory(matrixPowerOf_gpuxphi)
#add_subdirectory(matrixTimesMatrix_gpuxphi)

