cmake_minimum_required(VERSION 3.20)

# Common OpenCL options
if(SUPPORT_OPENCL)
	set(CTRL_EXAMPLES_OPENCL_GPU_PROFILING OFF) # Profiling with this
	set(CTRL_EXAMPLES_OPENCL_GPU_GENERATE_VISUAL_PROFILER OFF) # Complete ifo about events
	set(CTRL_EXAMPLES_OPENCL_GPU_LOCAL_SIZE "16") # Localsize
endif(SUPPORT_OPENCL)

if(SUPPORT_FPGA)
	set(CTRL_EXAMPLES_FPGA_PROFILING OFF) # Profiling with this
	set(CTRL_EXAMPLES_FPGA_GENERATE_VISUAL_PROFILER OFF) # Complete ifo about events
	set(CTRL_EXAMPLES_FPGA_LOCAL_SIZE_0 "16") # Localsize 0
	set(CTRL_EXAMPLES_FPGA_LOCAL_SIZE_1 "16") # Localsize 1
	set(CTRL_EXAMPLES_FPGA_LOCAL_SIZE_2 "0") # Localsize 0
endif(SUPPORT_FPGA)

if(SUPPORT_CUDA)
	set(CTRL_EXAMPLES_CUDA_BLOCKSIZE "16") # Block Size
endif(SUPPORT_CUDA)

if(SUPPORT_CPU)
	set(CTRL_EXAMPLES_CPU_BLOCKSIZE "16") # Block Size
endif(SUPPORT_CPU)

# === APPLY OPTIONS ===

# Debug and profiling
if(CTRL_EXAMPLES_OPENCL_GPU_PROFILING)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_EXAMPLES_OPENCL_GPU_PROFILING_ ")
	set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_EXAMPLES_OPENCL_GPU_PROFILING_ ")
endif(CTRL_EXAMPLES_OPENCL_GPU_PROFILING)

if(CTRL_EXAMPLES_OPENCL_GPU_GENERATE_VISUAL_PROFILER)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_EXAMPLES_OPENCL_GPU_GENERATE_VISUAL_PROFILER_ ")
	set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_EXAMPLES_OPENCL_GPU_GENERATE_VISUAL_PROFILER_ ")
endif(CTRL_EXAMPLES_OPENCL_GPU_GENERATE_VISUAL_PROFILER)

if(CTRL_EXAMPLES_FPGA_PROFILING)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_EXAMPLES_FPGA_PROFILING_ ")
	set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_EXAMPLES_FPGA_PROFILING_ ")
endif(CTRL_EXAMPLES_FPGA_PROFILING)

if(CTRL_EXAMPLES_FPGA_GENERATE_VISUAL_PROFILER)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_EXAMPLES_FPGA_GENERATE_VISUAL_PROFILER_ ")
	set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_EXAMPLES_FPGA_GENERATE_VISUAL_PROFILER_ ")
endif(CTRL_EXAMPLES_FPGA_GENERATE_VISUAL_PROFILER)

# Blocksizes
if(SUPPORT_OPENCL)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DLOCAL_SIZE=${CTRL_EXAMPLES_OPENCL_GPU_LOCAL_SIZE} ")
	set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -DLOCAL_SIZE=${CTRL_EXAMPLES_OPENCL_GPU_LOCAL_SIZE} ")
endif(SUPPORT_OPENCL)

if(SUPPORT_FPGA)
	set(
		CMAKE_C_FLAGS
		"${CMAKE_C_FLAGS} -DLOCAL_SIZE_0=${CTRL_EXAMPLES_FPGA_LOCAL_SIZE_0} -DLOCAL_SIZE_1=${CTRL_EXAMPLES_FPGA_LOCAL_SIZE_1} -DLOCAL_SIZE_2=${CTRL_EXAMPLES_FPGA_LOCAL_SIZE_2} -DKERNELTYPE=NDRANGE -DCTRL_KERNEL_PATH=${CTRL_KERNELS_PATH_FPGA} -DREF_KERNEL_PATH=${REF_KERNELS_PATH_FPGA}"
	)
	set(
		CMAKE_CXX_FLAGS
		"${CMAKE_CXX_FLAGS} -DLOCAL_SIZE_0=${CTRL_EXAMPLES_FPGA_LOCAL_SIZE_0} -DLOCAL_SIZE_1=${CTRL_EXAMPLES_FPGA_LOCAL_SIZE_1} -DLOCAL_SIZE_2=${CTRL_EXAMPLES_FPGA_LOCAL_SIZE_2} -DKERNELTYPE=NDRANGE -DCTRL_KERNEL_PATH=${CTRL_KERNELS_PATH_FPGA} -DREF_KERNEL_PATH=${REF_KERNELS_PATH_FPGA}"
	)
endif(SUPPORT_FPGA)

if(SUPPORT_CUDA)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DBLOCKSIZE=${CTRL_EXAMPLES_CUDA_BLOCKSIZE} ")
	set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -DBLOCKSIZE=${CTRL_EXAMPLES_CUDA_BLOCKSIZE} ")
endif(SUPPORT_CUDA)

if(SUPPORT_CPU)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DBLOCKSIZE=${CTRL_EXAMPLES_CPU_BLOCKSIZE} ")
	set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -DBLOCKSIZE=${CTRL_EXAMPLES_CPU_BLOCKSIZE} ")
endif(SUPPORT_CPU)

# Include directories
include_directories(${CTRL_INCLUDE_DIRS})

# Compile (CUDA must be enabled)
if(SUPPORT_CUDA)
	add_executable(Mandelbrot_Animation src/Mandelbrot_Animation.cu)
	target_link_libraries(Mandelbrot_Animation ${CTRL_LIBS})
endif(SUPPORT_CUDA)
