cmake_minimum_required(VERSION 3.20)

# Common files and include dirs
set(CTRL_INCLUDE_DIRS ${CTRL_INCLUDE_DIRS} ${CMAKE_SOURCE_DIR}/Ctrl/inc)
set(CTRL_SOURCES ${CTRL_SOURCES} src/Core/Ctrl_Core.c src/Core/Ctrl_Config.c)

# Support for Cpu
if(SUPPORT_CPU)
	set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_ARCH_CPU_ ")
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_ARCH_CPU_ ")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_CTRL_ARCH_CPU_ ")

	set(CTRL_SOURCES ${CTRL_SOURCES} src/Architectures/Cpu/Ctrl_Cpu.c)

	# MKL support
	if(MKL)
		set(BLA_VENDOR Intel10_64lp)
		find_package(BLAS REQUIRED)
		set(CTRL_LIBS ${CTRL_LIBS} ${BLAS_LIBRARIES})
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_MKL_ ")
		set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_MKL_ ")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_CTRL_MKL_ ")
	endif(MKL)
endif(SUPPORT_CPU)

# Support for OpenCl Gpu
if(SUPPORT_OPENCL)
	if(OPENCL_GPU_ERROR_CHECK)
		set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_OPENCL_ERROR_CHECK_ ")
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_OPENCL_ERROR_CHECK_ ")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_CTRL_OPENCL_ERROR_CHECK_ ")
	endif(OPENCL_GPU_ERROR_CHECK)

	if(OPENCL_GPU_TEST_OUTPUT)
		set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_OPENCL_GPU_TEST_OUTPUT_ ")
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_OPENCL_GPU_TEST_OUTPUT_ ")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_OPENCL_GPU_TEST_OUTPUT_ ")
	endif(OPENCL_GPU_TEST_OUTPUT)

	if(OPENCL_GPU_PROFILING)
		set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_OPENCL_GPU_PROFILING_ ")
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_OPENCL_GPU_PROFILING_ ")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_CTRL_OPENCL_GPU_PROFILING_ ")

		set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_OPENCL_GPU_PROFILING_N_READ_TASKS_=${OPENCL_GPU_PROFILING_N_READ_TASKS} ")
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_OPENCL_GPU_PROFILING_N_READ_TASKS_=${OPENCL_GPU_PROFILING_N_READ_TASKS} ")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_OPENCL_GPU_PROFILING_N_READ_TASKS_=${OPENCL_GPU_PROFILING_N_READ_TASKS} ")

		set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_OPENCL_GPU_PROFILING_N_WRITE_TASKS_=${OPENCL_GPU_PROFILING_N_WRITE_TASKS} ")
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_OPENCL_GPU_PROFILING_N_WRITE_TASKS_=${OPENCL_GPU_PROFILING_N_WRITE_TASKS} ")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_OPENCL_GPU_PROFILING_N_WRITE_TASKS_=${OPENCL_GPU_PROFILING_N_WRITE_TASKS} ")

		set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_OPENCL_GPU_PROFILING_N_KERNEL_TASKS_=${OPENCL_GPU_PROFILING_N_KERNEL_TASKS} ")
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_OPENCL_GPU_PROFILING_N_KERNEL_TASKS_=${OPENCL_GPU_PROFILING_N_KERNEL_TASKS} ")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_OPENCL_GPU_PROFILING_N_KERNEL_TASKS_=${OPENCL_GPU_PROFILING_N_KERNEL_TASKS} ")

		if(OPENCL_GPU_PROFILING_VERBOSE)
			set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_OPENCL_GPU_PROFILING_VERBOSE_ ")
			set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_OPENCL_GPU_PROFILING_VERBOSE_ ")
			set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_CTRL_OPENCL_GPU_PROFILING_VERBOSE_ ")
		endif(OPENCL_GPU_PROFILING_VERBOSE)
	endif(OPENCL_GPU_PROFILING)

	set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_ARCH_OPENCL_GPU_ ")
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_ARCH_OPENCL_GPU_ ")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_CTRL_ARCH_OPENCL_GPU_ ")

	set(CTRL_SOURCES ${CTRL_SOURCES} src/Architectures/OpenCL/Ctrl_OpenCL_Gpu.c)
endif(SUPPORT_OPENCL)

if(SUPPORT_FPGA)
	if(OPENCL_GPU_ERROR_CHECK)
		set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_OPENCL_ERROR_CHECK_ ")
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_OPENCL_ERROR_CHECK_ ")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_CTRL_OPENCL_ERROR_CHECK_ ")
	endif(OPENCL_GPU_ERROR_CHECK)

	if(FPGA_TEST_OUTPUT)
		set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_FPGA_TEST_OUTPUT_ ")
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_FPGA_TEST_OUTPUT_ ")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_FPGA_TEST_OUTPUT_ ")
	endif(FPGA_TEST_OUTPUT)

	if(FPGA_PROFILING)
		set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_FPGA_PROFILING_ ")
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_FPGA_PROFILING_ ")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_CTRL_FPGA_PROFILING_ ")

		set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_FPGA_PROFILING_N_READ_TASKS_=${FPGA_PROFILING_N_READ_TASKS} ")
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_FPGA_PROFILING_N_READ_TASKS_=${FPGA_PROFILING_N_READ_TASKS} ")
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_FPGA_PROFILING_N_READ_TASKS_=${FPGA_PROFILING_N_READ_TASKS} ")

		set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_FPGA_PROFILING_N_WRITE_TASKS_=${FPGA_PROFILING_N_WRITE_TASKS} ")
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_FPGA_PROFILING_N_WRITE_TASKS_=${FPGA_PROFILING_N_WRITE_TASKS} ")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_FPGA_PROFILING_N_WRITE_TASKS_=${FPGA_PROFILING_N_WRITE_TASKS} ")

		set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_FPGA_PROFILING_N_KERNEL_TASKS_=${FPGA_PROFILING_N_KERNEL_TASKS} ")
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_FPGA_PROFILING_N_KERNEL_TASKS_=${FPGA_PROFILING_N_KERNEL_TASKS} ")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_FPGA_PROFILING_N_KERNEL_TASKS_=${FPGA_PROFILING_N_KERNEL_TASKS} ")

		if(FPGA_PROFILING_VERBOSE)
			set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_FPGA_PROFILING_VERBOSE_ ")
			set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_FPGA_PROFILING_VERBOSE_ ")
			set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_CTRL_FPGA_PROFILING_VERBOSE_ ")
		endif(FPGA_PROFILING_VERBOSE)
	endif(FPGA_PROFILING)

	set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_ARCH_FPGA_ ")
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_ARCH_FPGA_ ")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_CTRL_ARCH_FPGA_ ")

	set(CTRL_SOURCES ${CTRL_SOURCES} src/Architectures/FPGA/Ctrl_FPGA.c)
endif(SUPPORT_FPGA)

# Support for CUDA
if(SUPPORT_CUDA)
	if(CUDA_ERROR_CHECK)
		set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_CUDA_ERROR_CHECK_ ")
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_CUDA_ERROR_CHECK_ ")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_CTRL_CUDA_ERROR_CHECK_ ")
	endif(CUDA_ERROR_CHECK)

	set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_ARCH_CUDA_")
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_ARCH_CUDA_")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_CTRL_ARCH_CUDA_")

	set(CTRL_SOURCES ${CTRL_SOURCES} src/Architectures/Cuda/Ctrl_Cuda.c)

	# CUBLAS support
	if(CUBLAS)
		set(CTRL_LIBS ${CTRL_LIBS} CUDA::cublas)
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_CUBLAS_ ")
		set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_CUBLAS_ ")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_CTRL_CUBLAS_ ")
	endif(CUBLAS)

	# Magma support
	if(MAGMA)
		set(CTRL_INCLUDE_DIRS ${CTRL_INCLUDE_DIRS} ${MAGMA_ROOT}/include)
		set(CTRL_LIBS ${CTRL_LIBS} ${MAGMA_ROOT}/lib/libmagma.so)
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_MAGMA_ -DADD_ ")
		set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_MAGMA_ -DADD_ ")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_CTRL_MAGMA_ -DADD_ ")
	endif(MAGMA)
endif(SUPPORT_CUDA)

# Support for HIP
if(SUPPORT_HIP)
	if(HIP_ERROR_CHECK)
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_HIP_ERROR_CHECK_ ")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_CTRL_HIP_ERROR_CHECK_ ")
		set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_HIP_ERROR_CHECK_ ")
	endif(HIP_ERROR_CHECK)

	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_CTRL_ARCH_HIP_")
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_ARCH_HIP_")

	set(CTRL_SOURCES ${CTRL_SOURCES} src/Architectures/Hip/Ctrl_Hip.c)

	# HIPBLAS support
	if(HIPBLAS)
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_HIPBLAS_ ")
		set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_HIPBLAS_ ")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_CTRL_HIPBLAS_ ")
	endif(HIPBLAS)
endif(SUPPORT_HIP)

if(CTRL_CMAKE_VERBOSE_CTRL)
	message(STATUS "CTRL_CPU = ${SUPPORT_CPU}")
	message(STATUS "CTRL_CUDA = ${SUPPORT_CUDA}")
	message(STATUS "CTRL_HIP = ${SUPPORT_HIP}")
	message(STATUS "CTRL_OPENCL_GPU = ${SUPPORT_OPENCL}")
	message(STATUS "CTRL_FPGA = ${SUPPORT_FPGA}")
	message(STATUS "CTRL_C vars = ${CMAKE_C_FLAGS}")
	message(STATUS "CTRL_CXX vars = ${CMAKE_CXX_FLAGS}")
	message(STATUS "CTRL_CUDA vars = ${CMAKE_CUDA_FLAGS}")
	message(STATUS "CTRL_INCLUDE DIRS = ${CTRL_INCLUDE_DIRS}")
	message(STATUS "CTRL_SOURCES = ${CTRL_SOURCES}")
	message(STATUS "CTRL_LIBS = ${CTRL_LIBS}")
endif(CTRL_CMAKE_VERBOSE_CTRL)

# Include all directories
include_directories(${CTRL_INCLUDE_DIRS})

# Build the library
add_library(Ctrl SHARED ${CTRL_SOURCES})
target_link_libraries(Ctrl ${CTRL_LIBS})
set_target_properties(
	Ctrl
	PROPERTIES VERSION ${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_REVISION} SOVERSION ${VERSION_MAJOR}
)

# Update parent vars
set(CTRL_LIBS ${CTRL_LIBS} PARENT_SCOPE)
set(CTRL_INCLUDE_DIRS ${CTRL_INCLUDE_DIRS} PARENT_SCOPE)
set(CMAKE_C_FLAGS ${CMAKE_C_FLAGS} PARENT_SCOPE)
set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} PARENT_SCOPE)
set(CMAKE_CUDA_FLAGS ${CMAKE_CUDA_FLAGS} PARENT_SCOPE)
