cmake_minimum_required (VERSION 3.20)

# Common OpenCL options
if (SUPPORT_OPENCL)
	set(CTRL_EXAMPLES_OPENCL_GPU_PROFILING OFF) # Profiling with this
	set(CTRL_EXAMPLES_OPENCL_GPU_GENERATE_VISUAL_PROFILER OFF) # Complete ifo about events
	set(CTRL_EXAMPLES_OPENCL_GPU_LOCAL_SIZE_0 "16") # Localsize x j
	set(CTRL_EXAMPLES_OPENCL_GPU_LOCAL_SIZE_1 "16") # Localsize y i
endif (SUPPORT_OPENCL)

if (SUPPORT_FPGA)
	set(CTRL_EXAMPLES_FPGA_LOCAL_SIZE_0 "16") # Localsize x j
	set(CTRL_EXAMPLES_FPGA_LOCAL_SIZE_1 "16") # Localsize y i
endif (SUPPORT_FPGA)

if (SUPPORT_CUDA)
	set(CTRL_EXAMPLES_CUDA_BLOCKSIZE_0 "16") # Block Size x j
	set(CTRL_EXAMPLES_CUDA_BLOCKSIZE_1 "16") # Block Size y i
endif (SUPPORT_CUDA)

if (SUPPORT_HIP)
	set(CTRL_EXAMPLES_HIP_BLOCKSIZE_0 "16") # Block Size x j
	set(CTRL_EXAMPLES_HIP_BLOCKSIZE_1 "16") # Block Size y i
endif (SUPPORT_HIP)

if (SUPPORT_CPU)
	set(CTRL_EXAMPLES_CPU_BLOCKSIZE_0 "16") # Block Size x j
	set(CTRL_EXAMPLES_CPU_BLOCKSIZE_1 "16") # Block Size y i
endif (SUPPORT_CPU)

# Apply options
if (CTRL_EXAMPLES_OPENCL_GPU_PROFILING)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_EXAMPLES_OPENCL_GPU_PROFILING_ ")
	set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_EXAMPLES_OPENCL_GPU_PROFILING_ ")
endif (CTRL_EXAMPLES_OPENCL_GPU_PROFILING)

if (CTRL_EXAMPLES_OPENCL_GPU_GENERATE_VISUAL_PROFILER)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_CTRL_EXAMPLES_OPENCL_GPU_GENERATE_VISUAL_PROFILER_ ")
	set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -D_CTRL_EXAMPLES_OPENCL_GPU_GENERATE_VISUAL_PROFILER_ ")
endif (CTRL_EXAMPLES_OPENCL_GPU_GENERATE_VISUAL_PROFILER)

if (SUPPORT_OPENCL)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DLOCAL_SIZE_0=${CTRL_EXAMPLES_OPENCL_GPU_LOCAL_SIZE_0} -DLOCAL_SIZE_1=${CTRL_EXAMPLES_OPENCL_GPU_LOCAL_SIZE_1} ")
	set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -DLOCAL_SIZE_0=${CTRL_EXAMPLES_OPENCL_GPU_LOCAL_SIZE_0} -DLOCAL_SIZE_1=${CTRL_EXAMPLES_OPENCL_GPU_LOCAL_SIZE_1} ")
endif(SUPPORT_OPENCL)

if (SUPPORT_FPGA)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DLOCAL_SIZE_0=${CTRL_EXAMPLES_FPGA_LOCAL_SIZE_0} -DLOCAL_SIZE_1=${CTRL_EXAMPLES_FPGA_LOCAL_SIZE_1} -DKERNELTYPE=TASK -DCTRL_KERNEL_PATH=${CTRL_KERNELS_PATH_FPGA} -DREF_KERNEL_PATH=${REF_KERNELS_PATH_FPGA}")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DLOCAL_SIZE_0=${CTRL_EXAMPLES_FPGA_LOCAL_SIZE_0} -DLOCAL_SIZE_1=${CTRL_EXAMPLES_FPGA_LOCAL_SIZE_1} -DKERNELTYPE=TASK -DCTRL_KERNEL_PATH=${CTRL_KERNELS_PATH_FPGA} -DREF_KERNEL_PATH=${REF_KERNELS_PATH_FPGA}")
endif(SUPPORT_FPGA)

if (SUPPORT_CUDA)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DBLOCKSIZE_0=${CTRL_EXAMPLES_CUDA_BLOCKSIZE_0} -DBLOCKSIZE_1=${CTRL_EXAMPLES_CUDA_BLOCKSIZE_1} ")
	set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -DBLOCKSIZE_0=${CTRL_EXAMPLES_CUDA_BLOCKSIZE_0} -DBLOCKSIZE_1=${CTRL_EXAMPLES_CUDA_BLOCKSIZE_1} ")
endif(SUPPORT_CUDA)

if (SUPPORT_HIP)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DBLOCKSIZE_0=${CTRL_EXAMPLES_HIP_BLOCKSIZE_0} -DBLOCKSIZE_1=${CTRL_EXAMPLES_HIP_BLOCKSIZE_1} ")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DBLOCKSIZE_0=${CTRL_EXAMPLES_HIP_BLOCKSIZE_0} -DBLOCKSIZE_1=${CTRL_EXAMPLES_HIP_BLOCKSIZE_1} ")
endif(SUPPORT_HIP)

if (SUPPORT_CPU)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DBLOCKSIZE_0=${CTRL_EXAMPLES_CPU_BLOCKSIZE_0} -DBLOCKSIZE_1=${CTRL_EXAMPLES_CPU_BLOCKSIZE_1} ")
	set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -DBLOCKSIZE_0=${CTRL_EXAMPLES_CPU_BLOCKSIZE_0} -DBLOCKSIZE_1=${CTRL_EXAMPLES_CPU_BLOCKSIZE_1} ")
endif(SUPPORT_CPU)

# Verbose
if (CTRL_CMAKE_VERBOSE_EXAMPLES_HOTSPOT)
	message(STATUS "HOTSPOT_INCLUDE DIRS = ${CTRL_INCLUDE_DIRS}")
	message(STATUS "HOTSPOT_LIBS = ${CTRL_LIBS}")
	message(STATUS "HOTSPOT_CTRL_C vars = ${CMAKE_C_FLAGS}")
	message(STATUS "HOTSPOT_CTRL_CXX vars = ${CMAKE_CXX_FLAGS}")
	message(STATUS "HOTSPOT_CTRL_CUDA vars = ${CMAKE_CUDA_FLAGS}")
endif(CTRL_CMAKE_VERBOSE_EXAMPLES_HOTSPOT)

# Include directories
include_directories(${CTRL_INCLUDE_DIRS})

# OpenCL
if (SUPPORT_OPENCL)
	add_executable(Hotspot_OpenCL_Gpu_Ctrl src/Hotspot_OpenCL_Gpu_Ctrl.c)
	target_link_libraries(Hotspot_OpenCL_Gpu_Ctrl ${CTRL_LIBS})

	add_executable(Hotspot_OpenCL_Gpu_Ref_Async src/Hotspot_OpenCL_Gpu_Ref_Async.c)
	target_link_libraries(Hotspot_OpenCL_Gpu_Ref_Async ${CTRL_LIBS})
	
	add_executable(Hotspot_OpenCL_Gpu_Ref_Sync src/Hotspot_OpenCL_Gpu_Ref_Sync.c)
	target_link_libraries(Hotspot_OpenCL_Gpu_Ref_Sync ${CTRL_LIBS})
endif (SUPPORT_OPENCL)

#FPGA
if (SUPPORT_FPGA)
	add_executable(Hotspot_FPGA_Ctrl src/Hotspot_FPGA_Ctrl.c)
	target_link_libraries(Hotspot_FPGA_Ctrl ${CTRL_LIBS})

    add_custom_command(OUTPUT ${CMAKE_CURRENT_SOURCE_DIR}/src/Hotspot_Ctrl.aocx
        COMMAND aoc ${AOC_CTRL_DEFS} ${AOC_CTRL_INCLUDES} ${CMAKE_CURRENT_SOURCE_DIR}/src/Hotspot_FPGA_Ctrl.cl -o ${CMAKE_CURRENT_SOURCE_DIR}/src/Hotspot_Ctrl.aocx ${FPGA_AOC_FLAGS}
        DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/src/Hotspot_FPGA_Ctrl.cl)
    add_custom_target(Hotspot_FPGA_Ctrl_kernel DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/src/Hotspot_Ctrl.aocx ${CMAKE_CURRENT_SOURCE_DIR}/src/Hotspot_FPGA_Ctrl.cl)
    add_dependencies(Hotspot_FPGA_Ctrl Hotspot_FPGA_Ctrl_kernel)

	add_executable(Hotspot_FPGA_Ref_Async src/Hotspot_FPGA_Ref_Async.c)
	add_executable(Hotspot_FPGA_Ref_Sync src/Hotspot_FPGA_Ref_Sync.c)

	target_link_libraries(Hotspot_FPGA_Ref_Async ${CTRL_LIBS})
	target_link_libraries(Hotspot_FPGA_Ref_Sync ${CTRL_LIBS})

    add_custom_command(OUTPUT ${CMAKE_CURRENT_SOURCE_DIR}/src/Hotspot_Ref.aocx
        COMMAND aoc ${CMAKE_CURRENT_SOURCE_DIR}/src/Hotspot_FPGA_Ref.cl -o ${CMAKE_CURRENT_SOURCE_DIR}/src/Hotspot_Ref.aocx ${FPGA_AOC_FLAGS}
        DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/src/Hotspot_FPGA_Ref.cl)
    add_custom_target(Hotspot_FPGA_Ref_kernel DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/src/Hotspot_Ref.aocx ${CMAKE_CURRENT_SOURCE_DIR}/src/Hotspot_FPGA_Ref.cl)
	add_dependencies(Hotspot_FPGA_Ref_Async Hotspot_FPGA_Ref_kernel)
	add_dependencies(Hotspot_FPGA_Ref_Sync Hotspot_FPGA_Ref_kernel)
endif (SUPPORT_FPGA)

# Cuda
if (SUPPORT_CUDA)
	add_executable(Hotspot_Cuda_Ctrl src/Hotspot_Cuda_Ctrl.cu)
	target_link_libraries(Hotspot_Cuda_Ctrl ${CTRL_LIBS})

	add_executable(Hotspot_Cuda_Ref_Async src/Hotspot_Cuda_Ref_Async.cu)
	target_link_libraries(Hotspot_Cuda_Ref_Async ${CTRL_LIBS})

	add_executable(Hotspot_Cuda_Ref_Sync src/Hotspot_Cuda_Ref_Sync.cu)
	target_link_libraries(Hotspot_Cuda_Ref_Sync ${CTRL_LIBS})
endif (SUPPORT_CUDA)

# Hip
if (SUPPORT_HIP)
	add_executable(Hotspot_Hip_Ctrl src/Hotspot_Hip_Ctrl.cpp)
	target_link_libraries(Hotspot_Hip_Ctrl ${CTRL_LIBS})

	add_executable(Hotspot_Hip_Ref_Async src/Hotspot_Hip_Ref_Async.cpp)
	target_link_libraries(Hotspot_Hip_Ref_Async ${CTRL_LIBS})

	add_executable(Hotspot_Hip_Ref_Sync src/Hotspot_Hip_Ref_Sync.cpp)
	target_link_libraries(Hotspot_Hip_Ref_Sync ${CTRL_LIBS})
endif (SUPPORT_HIP)

if(SUPPORT_CPU)
	add_executable(Hotspot_Cpu_Ctrl src/Hotspot_Cpu_Ctrl.c)
	target_link_libraries(Hotspot_Cpu_Ctrl ${CTRL_LIBS})

	add_executable(Hotspot_Cpu_Ref_Sync src/Hotspot_Cpu_Ref_Sync.c)
	target_link_libraries(Hotspot_Cpu_Ref_Sync ${CTRL_LIBS})
endif (SUPPORT_CPU)
