#!/bin/bash
#
# Script for testing the correct results of jacobiMultidim with some examples
#
# (c) 2025 Arturo Gonzalez-Escribano
#

# 1. EXPERIMENT INFORMATION
# 1.1. APP NAME AND DEFAULT EXECUTABLES LIST
APP_NAME="Stencil Multidim"
EXE_NAMES="../../build/examples/Jacobi_Multidim/Jacobi_Multidim_Ctrl"
DEVICE_FILE_PATH="../../examples/Device_Selection_Files/dev_epsilod_exp"

# 1.2. APP/EXPERIMENT SPECIFIC PARAMETERS
PROCS="1 2 3 4"

# 1.3. DIRECTORY WITH THE FILES CONTAINING THE EXPECTED RESULTS
RESULT_DIR=CorrectResults

# 1.4. NAME OF THE RESULTS FILE GENERATED BY THE EXECUTABLES
RESULT_FILE="Result.out.txt"

# 1.5. MPI RUN COMMAND
if [ -z "$MPI_RUN" ]; then
	MPI_RUN="srun --mpi=pmi2 -Q -K -w manticore --exclusive --cpus-per-task=8 "
fi

# 2. WRITE HEADER
echo
echo TESTING SCRIPT
echo --------------
echo "APPLICATION: $APP_NAME"
echo "EXECUTABLES: $EXE_NAMES"
echo

# 3.3. CHECK THAT EXECUTABLES HAVE BEEN GENERATED
for name in $EXE_NAMES; do
	OK=y
	if [ ! -x $name ]; then
		echo "Error: Executable not found -- $name"
		OK=n
	fi
done
if [ $OK != y ]; then
	echo
	echo -e "\tBefore using this script generate the executables with:  $ make check"
	echo
	exit 1
fi

# 4. TESTING EXPERIMENT
function doTest() {
	echo -e "\e[1mTest $2 $3:\e[0m"

	export TEST_WRITE_OUTPUT=array
	export HIT_FILE_TEXT=y
	export HIT_FILE_HEADER=n
	export HIT_FILE_TXT_SIZE=21
	export HIT_FILE_TXT_DECIMALS=18

	# EXECUTE PROGRAM
	rm -f $RESULT_FILE
	echo -e "\t$MPI_RUN -n $2 ./$1 $3 $DEVICE_FILE_PATH >/dev/null 2>check.err"
	$MPI_RUN -n $2 ./$1 $3 $DEVICE_FILE_PATH >/dev/null 2>check.err

	# EXECUTION ERRORS, SKIP TESTING RESULT FILE
	if [ 0 != $? ]; then
		echo -e "\e[31mERROR EXECUTING\e[0m: $(cat check.err)"
	fi

	# NOTE workaround nfs system in trasgo cluster not detecting the file immediately
	ls &>/dev/null

	# IF THE RESULTS FILE HAS NOT BEEN GENERATED
	if [ ! -r $RESULT_FILE ]; then
		echo -e "\e[31mERROR\e[0m: The executable \"$exe\" does no generate an ouput file."
		echo
		exit -1
	# CHECK THE CONTENTS OF THE RESULTS FILE
	else
		CHECK=""
		diff $RESULT_FILE $RESULT_DIR/Result.${3// /.} >/dev/null || CHECK=Result
		if [ "$CHECK" != "" ]; then
			echo -e "\e[31mERROR\e[0m: $CHECK"
		else
			echo -e "\e[32mOK\e[0m"
		fi
	fi
}

# 5. LOOPS FOR TESTS
for exe in $EXE_NAMES; do
	echo
	echo "Testing: $exe"
	echo "------------------------"
	for proc in $PROCS; do
		doTest $exe $proc "100 200"
		doTest $exe $proc "22 14 200"
		doTest $exe $proc "18 20 12 200"
		doTest $exe $proc "20 15 10 8 100"
	done
done

# 6. CLEAN
rm -f $RESULT_FILE
rm -f check.err
