cmake_minimum_required (VERSION 2.6)

# Añadimos los directorios
# add_subdirectory(matrixAdd)
add_subdirectory(matrixMult)
add_subdirectory(matrixMultBlocks)
add_subdirectory(cellAutom)
add_subdirectory(cellAutomTMP)
# add_subdirectory(BlackScholes)

# add_subdirectory(gemver)
# add_subdirectory(matrixPowerOf)
